import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { io } from 'socket.io-client';
import { useEffect, useState } from 'react';
import { makeRequest } from '../../components/utilFunctions';
import Link from 'next/link';

const backendServer = 'http://127.0.0.1:5001';

const inter = Inter({ subsets: ['latin'] })
// const socket = io(backendServer);

// socket.on("connect", () => {
//     const engine = socket.io.engine;
//     console.log(engine.transport.name);
// });

export default function Home() {
    const [serverResponse, setServerResponse] = useState('');

    // const sendMessage = () => {
    //     socket.emit('send_message', {
    //         message: 'hello',
    //     })
    // }

    useEffect(() => {
        // socket.on('receive_message', (data) => {
        //     console.log(data)
        // })
        const fetchData = async () => {
            const result = await makeRequest(
                '/login',
                'POST',
                {
                    'Content-Type': 'application/json',
                    'Authorization': 'Basic ' + Buffer.from('boris:boris').toString('base64'),
                },
                JSON.stringify({
                    username: 'boris',
                    password: 'boris',
                    password2: 'boris',
                })
            )
            setServerResponse(result)
        }

        fetchData()
    }, [])

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>

                <h1 className={styles.title}>Chat Login</h1>

                <div className={styles.textfields}>
                    <label for="username">Username:</label>
                    <input type="text" id="username" name="username" />
                </div>

                <div className={styles.textfields}>
                    <label for="password">Password:</label>
                    <input type="password" id="password" name="password" />
                </div>

                <button className={styles.buttonLogin}>Login</button>

                <Link href='/' className={styles.register}>
                    <span>Register here if you don't have access</span>
                </Link>
                {/* <p>{serverResponse.token}</p> */}
            </main>
        </>
    )
}
